### ISSUE TITLE
Flutter Web Keyboard_shortcuts (work only alphabet keys) on Mac desktop and web)

### ISSUE THREAD

**Issue by abdulrehmananwar** [AntoineMarcel/keyboard_shortcuts#1]
shortcut keys not work with combination of keys. just working with alphabet keys on web and desktop
please help me in this regard
thanks

**Comment by AntoineMarcel** [comment]
Hello could you please send me the code please ?

**Comment by bynicodevelop** [comment]
It is the same for me.
Here is my code

Other than that, good job :D

```
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:keyboard_shortcuts/keyboard_shortcuts.dart';

void main() => runApp(App());

class App extends StatefulWidget {
  App({Key key}) : super(key: key);

  @override
  _AppState createState() => _AppState();
}

class _AppState extends State<App> {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Home(),
    );
  }
}

class Home extends StatefulWidget {
  Home({Key key}) : super(key: key);

  @override
  _HomeState createState() => _HomeState();
}

class _HomeState extends State<Home> {
  @override
  Widget build(BuildContext context) {
    return SafeArea(
      child: Scaffold(
        body: KeyBoardShortcuts(
          keysToPress: {
            LogicalKeyboardKey.controlLeft,
            LogicalKeyboardKey.keyN
          },
          onKeysPressed: () => print('cool'),
          child: Text('coucou'),
        ),
      ),
    );
  }
}
```

**Comment by AntoineMarcel** [comment]
Hi ! I published a new version with the correction for this problem ! 🙌

When we type shift or control etc.. in chrome Flutter RawKeyboard instance sended to the package that we pressed Shift Right and Shift Left or Control Right and Control Left. 
The problem was that the package verify if user type ControlLelt and KeyN and the instance send us that user type ControlerLeft ControlRight and KeyN so that can't work 😁

The solution was to verify in keys pressed if some name are Right and Left and ignore one of the two.

Thanks for your report, hope that it will working for you, appreciate to have feedback when you tried with the new version !
